### ISSUE TITLE
HPE UFT and TFS integration

### ISSUE THREAD

**Issue by vidulakulkarni5** [hpsa/ADM-TFS-Extension#9]
Microsoft VSIX Installation Fails.

I am using hpe uft 14.0.1 and TFS 2017 on Windows 7 Ultimate. when i followed the tutorial for tfs and uft integration here, the vsix installer was not installing. I got this message in log file:
This extension is not installable on any currently installed products.

Please let me know if there is any other way to Integrate tfs and uft

thanks in advance.

**Comment by EvanChen1989** [comment]
This error message happens when upload the extension file? It's not a executable file.

**Comment by vidulakulkarni5** [comment]
Hi EvanChen1989, 
when I try to upload the vsix installer file on tfs 2017, I get the warning: 
The Publisher Name supplied in the path (my name) must match the Name in the Publisher data 'uftpublisher'
